cmake_minimum_required(VERSION 3.13)
include(pico_sdk_import.cmake)
project(droidvibe_rp2040_logic_analyzer C CXX ASM)
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)
pico_sdk_init()
add_executable(droidvibe_rp2040_logic_analyzer main.c logic_capture.c)
pico_generate_pio_header(droidvibe_rp2040_logic_analyzer ${CMAKE_CURRENT_LIST_DIR}/logic_capture.pio)
target_link_libraries(droidvibe_rp2040_logic_analyzer pico_stdlib hardware_pio hardware_dma)
pico_enable_stdio_usb(droidvibe_rp2040_logic_analyzer 1)
pico_enable_stdio_uart(droidvibe_rp2040_logic_analyzer 0)
pico_add_extra_outputs(droidvibe_rp2040_logic_analyzer)